public class Class01 {
    public static void main(String[] args) {

        //V1 çalışmalarım...
        //V2kodları...
        //V3 çalışmalar...
        //V4
        
        //local'den sevgilerle
        //v5...
        //v6...
        
        
    }
}
